import type { Agent } from "@/lib/types"

export const mockAgents: Agent[] = [
  {
    id: "agent-001",
    name: "Customer Support Agent",
    description: "Handles customer inquiries, support tickets, and escalations with empathy and efficiency.",
    type: "customer-support",
    model: "gpt-4o",
    systemPrompt:
      "You are a helpful customer support agent. Respond with empathy, clarity, and efficiency. Always aim to resolve issues on the first contact.",
    maxTokens: 1500,
    temperature: 0.3,
    tools: ["web-search", "database-query", "email-sending"],
    status: "active",
    lifecycleStage: "production",
    version: "2.3.0",
    createdAt: "2024-01-15T09:00:00Z",
    updatedAt: "2025-04-15T14:30:00Z",
    createdBy: "user-001",
  },
  {
    id: "agent-002",
    name: "Data Analysis Agent",
    description: "Processes and analyzes large data sets, generates reports and actionable insights.",
    type: "analytics",
    model: "gpt-4o",
    systemPrompt:
      "You are a data analysis expert. Analyze the provided data thoroughly, identify trends, and present your findings in a clear, structured format.",
    maxTokens: 2000,
    temperature: 0.2,
    tools: ["database-query", "file-access", "code-execution"],
    status: "active",
    lifecycleStage: "production",
    version: "1.8.0",
    createdAt: "2024-02-20T10:00:00Z",
    updatedAt: "2025-03-28T11:15:00Z",
    createdBy: "user-002",
  },
  {
    id: "agent-003",
    name: "Content Generator",
    description: "Creates blog posts, social media content, marketing copy, and creative writing.",
    type: "creative",
    model: "claude-3-opus",
    systemPrompt:
      "You are a creative content writer with expertise in marketing, social media, and blog writing. Create engaging, original content tailored to the specified audience and platform.",
    maxTokens: 2500,
    temperature: 0.8,
    tools: ["web-search"],
    status: "active",
    lifecycleStage: "production",
    version: "1.5.2",
    createdAt: "2024-03-10T08:00:00Z",
    updatedAt: "2025-02-14T16:45:00Z",
    createdBy: "user-001",
  },
  {
    id: "agent-004",
    name: "Scheduling Assistant",
    description: "Manages calendars, schedules appointments, and coordinates meetings across time zones.",
    type: "productivity",
    model: "gpt-3.5-turbo",
    systemPrompt:
      "You are an intelligent scheduling assistant. Manage calendar events, resolve conflicts, and optimise meeting schedules. Always confirm details before making changes.",
    maxTokens: 800,
    temperature: 0.1,
    tools: ["calendar-access", "email-sending"],
    status: "inactive",
    lifecycleStage: "maintenance",
    version: "1.2.0",
    createdAt: "2024-04-05T12:00:00Z",
    updatedAt: "2025-01-10T09:30:00Z",
    createdBy: "user-003",
  },
  {
    id: "agent-005",
    name: "Research Agent",
    description: "Conducts in-depth market research, competitive analysis, and synthesises findings.",
    type: "research",
    model: "gpt-4",
    systemPrompt:
      "You are a research specialist with expertise in market analysis and competitive intelligence. Provide thorough, well-cited analysis based on available information.",
    maxTokens: 3000,
    temperature: 0.4,
    tools: ["web-search", "file-access", "database-query"],
    status: "active",
    lifecycleStage: "production",
    version: "2.0.1",
    createdAt: "2024-05-12T14:00:00Z",
    updatedAt: "2025-04-01T13:20:00Z",
    createdBy: "user-002",
  },
  {
    id: "agent-006",
    name: "Email Assistant",
    description: "Drafts, sends, and manages email follow-ups and communication workflows.",
    type: "communication",
    model: "gpt-3.5-turbo",
    systemPrompt:
      "You are a professional email assistant. Draft clear, concise, and professional emails. Match the tone to the context — formal for business, conversational for internal communications.",
    maxTokens: 1000,
    temperature: 0.5,
    tools: ["email-sending", "calendar-access"],
    status: "active",
    lifecycleStage: "development",
    version: "0.9.0",
    createdAt: "2025-01-20T11:00:00Z",
    updatedAt: "2025-03-15T10:00:00Z",
    createdBy: "user-001",
  },
  {
    id: "agent-007",
    name: "Code Review Agent",
    description: "Reviews code quality, identifies bugs, suggests improvements, and enforces coding standards.",
    type: "custom",
    model: "claude-3-sonnet",
    systemPrompt:
      "You are an expert code reviewer. Analyse code for bugs, security vulnerabilities, performance issues, and style violations. Provide actionable, constructive feedback.",
    maxTokens: 2000,
    temperature: 0.2,
    tools: ["code-execution", "file-access"],
    status: "error",
    lifecycleStage: "development",
    version: "0.5.0",
    createdAt: "2025-02-10T09:00:00Z",
    updatedAt: "2025-04-10T08:45:00Z",
    createdBy: "user-003",
  },
  {
    id: "agent-008",
    name: "HR Onboarding Agent",
    description: "Guides new employees through onboarding, answers HR policy questions, and collects documents.",
    type: "custom",
    model: "gpt-4o",
    systemPrompt:
      "You are a friendly HR onboarding specialist. Guide new employees through the onboarding process, answer questions about company policies, and help collect required documents.",
    maxTokens: 1200,
    temperature: 0.4,
    tools: ["email-sending", "file-access", "database-query"],
    status: "active",
    lifecycleStage: "production",
    version: "1.1.0",
    createdAt: "2024-08-01T10:00:00Z",
    updatedAt: "2025-03-20T15:30:00Z",
    createdBy: "user-002",
  },
]
