import type {
  LifecycleStageSummary,
  LifecycleTransition,
  AgentVersion,
  AgentTemplate,
} from "@/lib/types"

export const mockStageSummaries: LifecycleStageSummary[] = [
  {
    stage: "development",
    label: "Development",
    count: 6,
    percentage: 33,
    colour: "hsl(205 75% 55%)",
    icon: "Code2",
    description: "Agents in active development and testing",
  },
  {
    stage: "production",
    label: "Production",
    count: 9,
    percentage: 50,
    colour: "hsl(152 60% 35%)",
    icon: "Rocket",
    description: "Live agents serving end users",
  },
  {
    stage: "maintenance",
    label: "Maintenance",
    count: 2,
    percentage: 11,
    colour: "hsl(38 90% 50%)",
    icon: "Wrench",
    description: "Agents undergoing updates or tuning",
  },
  {
    stage: "retirement",
    label: "Retirement",
    count: 1,
    percentage: 6,
    colour: "hsl(215 35% 45%)",
    icon: "Archive",
    description: "Agents being decommissioned",
  },
]

export const mockLifecycleTransitions: LifecycleTransition[] = [
  {
    id: "lt-001",
    agentId: "agent-001",
    agentName: "Customer Support Agent",
    fromStage: "development",
    toStage: "production",
    transitionedAt: "2025-04-15T10:00:00Z",
    transitionedBy: "Jane Smith",
    reason: "All tests passed; approved for production deployment.",
  },
  {
    id: "lt-002",
    agentId: "agent-002",
    agentName: "Data Analysis Agent",
    fromStage: "maintenance",
    toStage: "production",
    transitionedAt: "2025-04-10T14:30:00Z",
    transitionedBy: "John Doe",
    reason: "Maintenance complete; performance benchmarks met.",
  },
  {
    id: "lt-003",
    agentId: "agent-007",
    agentName: "Code Review Agent",
    fromStage: "production",
    toStage: "maintenance",
    transitionedAt: "2025-04-08T09:15:00Z",
    transitionedBy: "Bob Johnson",
    reason: "Critical bug detected; moving to maintenance for hotfix.",
  },
  {
    id: "lt-004",
    agentId: "agent-004",
    agentName: "Scheduling Assistant",
    fromStage: "production",
    toStage: "maintenance",
    transitionedAt: "2025-03-30T11:00:00Z",
    transitionedBy: "Alice Brown",
    reason: "Scheduled maintenance window for model upgrade.",
  },
  {
    id: "lt-005",
    agentId: "agent-006",
    agentName: "Email Assistant",
    fromStage: "development",
    toStage: "production",
    transitionedAt: "2025-03-25T16:00:00Z",
    transitionedBy: "Jane Smith",
    reason: "Beta testing complete; ready for production.",
  },
  {
    id: "lt-006",
    agentId: "agent-005",
    agentName: "Research Agent",
    fromStage: "development",
    toStage: "production",
    transitionedAt: "2025-03-18T12:45:00Z",
    transitionedBy: "John Doe",
  },
  {
    id: "lt-007",
    agentId: "agent-003",
    agentName: "Content Generator",
    fromStage: "maintenance",
    toStage: "production",
    transitionedAt: "2025-03-10T10:00:00Z",
    transitionedBy: "Alice Brown",
    reason: "New model integrated and validated.",
  },
  {
    id: "lt-008",
    agentId: "agent-008",
    agentName: "HR Onboarding Agent",
    fromStage: "development",
    toStage: "production",
    transitionedAt: "2025-02-28T09:30:00Z",
    transitionedBy: "Bob Johnson",
  },
  {
    id: "lt-009",
    agentId: "agent-001",
    agentName: "Customer Support Agent",
    fromStage: "maintenance",
    toStage: "production",
    transitionedAt: "2025-02-15T14:00:00Z",
    transitionedBy: "Jane Smith",
    reason: "Post-update validation complete.",
  },
  {
    id: "lt-010",
    agentId: "legacy-agent-001",
    agentName: "Legacy Email Assistant v1",
    fromStage: "production",
    toStage: "retirement",
    transitionedAt: "2025-02-01T11:30:00Z",
    transitionedBy: "John Doe",
    reason: "Replaced by Email Assistant v2; usage dropped to near zero.",
  },
]

export const mockAgentVersions: AgentVersion[] = [
  {
    id: "v-001",
    agentId: "agent-001",
    agentName: "Customer Support Agent",
    versionNumber: "2.3.0",
    changelog: "Added multi-step reasoning and improved response quality; reduced latency by 20%.",
    createdAt: "2025-04-15T10:00:00Z",
    createdBy: "John Doe",
    stage: "production",
  },
  {
    id: "v-002",
    agentId: "agent-001",
    agentName: "Customer Support Agent",
    versionNumber: "2.2.1",
    changelog: "Fixed API rate limiting issue; improved error handling for edge cases.",
    createdAt: "2025-03-28T09:00:00Z",
    createdBy: "Jane Smith",
    stage: "production",
  },
  {
    id: "v-003",
    agentId: "agent-001",
    agentName: "Customer Support Agent",
    versionNumber: "2.2.0",
    changelog: "Integrated knowledge base; enhanced context retention across sessions.",
    createdAt: "2025-03-10T10:00:00Z",
    createdBy: "Bob Johnson",
    stage: "maintenance",
  },
  {
    id: "v-004",
    agentId: "agent-002",
    agentName: "Data Analysis Agent",
    versionNumber: "1.8.0",
    changelog: "Added support for real-time streaming data; improved chart generation accuracy.",
    createdAt: "2025-04-10T14:00:00Z",
    createdBy: "Alice Brown",
    stage: "production",
  },
  {
    id: "v-005",
    agentId: "agent-002",
    agentName: "Data Analysis Agent",
    versionNumber: "1.7.2",
    changelog: "Performance optimisations; fixed memory leak in long-running analyses.",
    createdAt: "2025-03-15T11:30:00Z",
    createdBy: "John Doe",
    stage: "production",
  },
  {
    id: "v-006",
    agentId: "agent-003",
    agentName: "Content Generator",
    versionNumber: "1.5.2",
    changelog: "Upgraded to Claude 3 Opus for significantly improved creative output.",
    createdAt: "2025-02-14T16:00:00Z",
    createdBy: "Jane Smith",
    stage: "production",
  },
  {
    id: "v-007",
    agentId: "agent-003",
    agentName: "Content Generator",
    versionNumber: "1.5.1",
    changelog: "Bug fix: Resolved issue with long-form content truncation.",
    createdAt: "2025-01-28T10:30:00Z",
    createdBy: "Bob Johnson",
    stage: "maintenance",
  },
  {
    id: "v-008",
    agentId: "agent-005",
    agentName: "Research Agent",
    versionNumber: "2.0.1",
    changelog: "Improved web search accuracy; added citation tracking for all sources.",
    createdAt: "2025-04-01T13:00:00Z",
    createdBy: "Alice Brown",
    stage: "production",
  },
  {
    id: "v-009",
    agentId: "agent-005",
    agentName: "Research Agent",
    versionNumber: "2.0.0",
    changelog: "Major rewrite: New research pipeline with parallel source querying; 3× faster.",
    createdAt: "2025-03-01T09:00:00Z",
    createdBy: "John Doe",
    stage: "production",
  },
]

export const mockAgentTemplates: AgentTemplate[] = [
  {
    id: "tmpl-001",
    name: "Customer Support Bot",
    description: "Production-ready customer support agent with empathy-focused responses and ticket management.",
    type: "customer-support",
    model: "gpt-4o",
    systemPrompt:
      "You are a professional customer support specialist. Handle inquiries with empathy, resolve issues efficiently, and escalate when necessary.",
    maxTokens: 1500,
    temperature: 0.3,
    tools: ["web-search", "database-query", "email-sending"],
    category: "Customer Service",
    isOfficial: true,
  },
  {
    id: "tmpl-002",
    name: "Data Analyst",
    description: "Advanced analytics agent that processes data, generates reports, and provides actionable insights.",
    type: "analytics",
    model: "gpt-4o",
    systemPrompt:
      "You are a data analysis expert. Analyse data thoroughly, identify patterns, and present findings clearly.",
    maxTokens: 2500,
    temperature: 0.2,
    tools: ["database-query", "code-execution", "file-access"],
    category: "Analytics",
    isOfficial: true,
  },
  {
    id: "tmpl-003",
    name: "Content Creator",
    description: "Creative content agent for blogs, social media, marketing copy, and creative writing.",
    type: "creative",
    model: "claude-3-opus",
    systemPrompt:
      "You are a creative content writer. Produce engaging, original content tailored to the specified audience and platform.",
    maxTokens: 3000,
    temperature: 0.8,
    tools: ["web-search"],
    category: "Marketing",
    isOfficial: true,
  },
  {
    id: "tmpl-004",
    name: "Research Specialist",
    description: "Deep-research agent for market research, competitive intelligence, and literature reviews.",
    type: "research",
    model: "gpt-4",
    systemPrompt:
      "You are a research specialist. Conduct thorough research, synthesise findings, and provide well-cited analysis.",
    maxTokens: 4000,
    temperature: 0.3,
    tools: ["web-search", "file-access", "database-query"],
    category: "Research",
    isOfficial: false,
  },
  {
    id: "tmpl-005",
    name: "Email Automation Agent",
    description: "Automates email drafting, scheduling, and follow-up workflows.",
    type: "communication",
    model: "gpt-3.5-turbo",
    systemPrompt:
      "You are a professional email assistant. Draft clear, concise, and professional emails matching the required tone.",
    maxTokens: 1000,
    temperature: 0.4,
    tools: ["email-sending", "calendar-access"],
    category: "Communication",
    isOfficial: true,
  },
  {
    id: "tmpl-006",
    name: "Productivity Coach",
    description: "Helps teams manage schedules, prioritise tasks, and improve workflows.",
    type: "productivity",
    model: "gpt-4o",
    systemPrompt:
      "You are a productivity coach. Help users optimise their schedules, prioritise tasks, and build better workflows.",
    maxTokens: 1200,
    temperature: 0.5,
    tools: ["calendar-access", "email-sending"],
    category: "Productivity",
    isOfficial: false,
  },
  {
    id: "tmpl-007",
    name: "Code Reviewer",
    description: "Reviews code quality, identifies bugs, and suggests improvements aligned with best practices.",
    type: "custom",
    model: "claude-3-sonnet",
    systemPrompt:
      "You are an expert code reviewer. Identify bugs, security issues, and style violations. Provide actionable feedback.",
    maxTokens: 2000,
    temperature: 0.1,
    tools: ["code-execution", "file-access"],
    category: "Engineering",
    isOfficial: true,
  },
  {
    id: "tmpl-008",
    name: "HR Onboarding Specialist",
    description: "Guides new hires through the onboarding process and answers HR policy questions.",
    type: "custom",
    model: "gpt-4o",
    systemPrompt:
      "You are a friendly HR onboarding specialist. Guide new employees through onboarding and answer their questions.",
    maxTokens: 1200,
    temperature: 0.4,
    tools: ["email-sending", "file-access", "database-query"],
    category: "Human Resources",
    isOfficial: false,
  },
]
