import type { MarketplaceListing, MarketplaceKpis, MarketplaceSubscription } from "@/lib/types"

export const mockMarketplaceListings: MarketplaceListing[] = [
  {
    id: "listing-001",
    agentId: "agent-ext-001",
    title: "Omnichannel Support Pro",
    description:
      "Enterprise-grade customer support agent that handles tickets across email, chat, and social media. Integrates with Zendesk, Intercom, and Freshdesk for seamless escalation workflows.",
    category: "customer-support",
    authorName: "Aria Systems",
    authorId: "author-001",
    rating: 4.9,
    reviewCount: 312,
    downloadCount: 4800,
    version: "3.2.1",
    publishedAt: "2024-01-10T08:00:00Z",
    updatedAt: "2025-04-20T10:00:00Z",
    isFeatured: true,
    isInstalled: true,
    installedVersion: "3.1.0",
    iconName: "Headphones",
  },
  {
    id: "listing-002",
    agentId: "agent-ext-002",
    title: "Insight Analytics Engine",
    description:
      "Connects to your data warehouse and automatically generates executive summaries, anomaly alerts, and actionable dashboards. Supports BigQuery, Snowflake, and Redshift natively.",
    category: "analytics",
    authorName: "DataForge Labs",
    authorId: "author-002",
    rating: 4.8,
    reviewCount: 278,
    downloadCount: 3900,
    version: "2.5.0",
    publishedAt: "2024-02-14T09:00:00Z",
    updatedAt: "2025-03-30T14:00:00Z",
    isFeatured: true,
    isInstalled: false,
    iconName: "BarChart3",
  },
  {
    id: "listing-003",
    agentId: "agent-ext-003",
    title: "Creative Studio AI",
    description:
      "Full-stack content creation suite for marketing teams. Generates blog posts, ad copy, social captions, and email campaigns with brand voice consistency and SEO optimisation.",
    category: "creative",
    authorName: "Muse Digital",
    authorId: "author-003",
    rating: 4.7,
    reviewCount: 201,
    downloadCount: 3100,
    version: "1.9.3",
    publishedAt: "2024-03-05T10:00:00Z",
    updatedAt: "2025-02-18T11:00:00Z",
    isFeatured: true,
    isInstalled: false,
    iconName: "PenTool",
  },
  {
    id: "listing-004",
    agentId: "agent-ext-004",
    title: "TaskFlow Optimizer",
    description:
      "AI-powered task management agent that prioritises your backlog, drafts meeting agendas, and syncs with Jira, Asana, and Linear to keep your team on track every single day.",
    category: "productivity",
    authorName: "FlowLabs",
    authorId: "author-004",
    rating: 4.8,
    reviewCount: 355,
    downloadCount: 4200,
    version: "2.1.0",
    publishedAt: "2024-01-25T07:00:00Z",
    updatedAt: "2025-04-10T09:00:00Z",
    isFeatured: true,
    isInstalled: true,
    installedVersion: "2.0.1",
    iconName: "CheckSquare",
  },
  {
    id: "listing-005",
    agentId: "agent-ext-005",
    title: "Deep Research Assistant",
    description:
      "Autonomous research agent that scours academic databases, news archives, and the web to compile structured research reports with citations. Ideal for analysts and knowledge workers.",
    category: "research",
    authorName: "Scholaris AI",
    authorId: "author-005",
    rating: 4.9,
    reviewCount: 189,
    downloadCount: 2700,
    version: "1.4.2",
    publishedAt: "2024-04-01T11:00:00Z",
    updatedAt: "2025-04-05T16:00:00Z",
    isFeatured: true,
    isInstalled: false,
    iconName: "BookOpen",
  },
  {
    id: "listing-006",
    agentId: "agent-ext-006",
    title: "InboxZero Email Manager",
    description:
      "Intelligent email triage agent that categorises, summarises, and drafts replies for your inbox. Works with Gmail and Outlook. Reduces email processing time by up to 70%.",
    category: "communication",
    authorName: "Streamline IO",
    authorId: "author-006",
    rating: 4.6,
    reviewCount: 422,
    downloadCount: 5000,
    version: "2.8.0",
    publishedAt: "2024-01-08T06:00:00Z",
    updatedAt: "2025-04-22T08:00:00Z",
    isFeatured: true,
    isInstalled: false,
    iconName: "Mail",
  },
  {
    id: "listing-007",
    agentId: "agent-ext-007",
    title: "Ticket Triage Bot",
    description:
      "Automatically classifies and routes incoming support tickets to the right team. Uses NLP to detect urgency, sentiment, and category, cutting first-response times by half.",
    category: "customer-support",
    authorName: "SupportStack",
    authorId: "author-007",
    rating: 4.4,
    reviewCount: 134,
    downloadCount: 1800,
    version: "1.2.1",
    publishedAt: "2024-05-10T09:00:00Z",
    updatedAt: "2025-03-14T12:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "Ticket",
  },
  {
    id: "listing-008",
    agentId: "agent-ext-008",
    title: "Revenue Attribution Analyst",
    description:
      "Multi-touch attribution agent that breaks down marketing spend across channels and correlates it with closed revenue. Integrates with Salesforce, HubSpot, and Marketo.",
    category: "analytics",
    authorName: "RevOps.ai",
    authorId: "author-008",
    rating: 4.5,
    reviewCount: 98,
    downloadCount: 1400,
    version: "1.1.0",
    publishedAt: "2024-06-15T10:00:00Z",
    updatedAt: "2025-02-28T15:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "TrendingUp",
  },
  {
    id: "listing-009",
    agentId: "agent-ext-009",
    title: "Brand Voice Writer",
    description:
      "Fine-tuned on your brand guidelines to produce on-brand copy for any channel. Upload a style guide and watch it generate consistent, high-quality content at scale.",
    category: "creative",
    authorName: "BrandCraft AI",
    authorId: "author-009",
    rating: 4.3,
    reviewCount: 167,
    downloadCount: 2200,
    version: "1.6.0",
    publishedAt: "2024-04-20T08:00:00Z",
    updatedAt: "2025-01-30T10:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "Feather",
  },
  {
    id: "listing-010",
    agentId: "agent-ext-010",
    title: "Meeting Summariser",
    description:
      "Joins your video calls, transcribes the conversation, and delivers structured minutes with action items and owners within seconds of the meeting ending.",
    category: "productivity",
    authorName: "MeetMind",
    authorId: "author-010",
    rating: 4.6,
    reviewCount: 289,
    downloadCount: 3500,
    version: "2.0.0",
    publishedAt: "2024-02-28T09:00:00Z",
    updatedAt: "2025-03-20T13:00:00Z",
    isFeatured: false,
    isInstalled: true,
    installedVersion: "2.0.0",
    iconName: "Video",
  },
  {
    id: "listing-011",
    agentId: "agent-ext-011",
    title: "Competitive Intelligence Scout",
    description:
      "Monitors competitor websites, press releases, job postings, and social channels to deliver a weekly competitive intelligence briefing directly to your Slack or email.",
    category: "research",
    authorName: "Scout Analytics",
    authorId: "author-011",
    rating: 4.5,
    reviewCount: 112,
    downloadCount: 1600,
    version: "1.3.0",
    publishedAt: "2024-07-01T10:00:00Z",
    updatedAt: "2025-04-01T09:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "Eye",
  },
  {
    id: "listing-012",
    agentId: "agent-ext-012",
    title: "Slack Concierge",
    description:
      "An AI concierge that lives in your Slack workspace. Answers FAQs, onboards new team members, schedules standups, and keeps your channels clean and organised.",
    category: "communication",
    authorName: "WorkBot Co",
    authorId: "author-012",
    rating: 4.4,
    reviewCount: 245,
    downloadCount: 2900,
    version: "1.7.1",
    publishedAt: "2024-03-18T08:00:00Z",
    updatedAt: "2025-02-10T11:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "MessageSquare",
  },
  {
    id: "listing-013",
    agentId: "agent-ext-013",
    title: "Churn Prediction Sentinel",
    description:
      "Proactively identifies at-risk customers by analysing usage patterns, NPS scores, and support history. Triggers automated re-engagement workflows before churn occurs.",
    category: "analytics",
    authorName: "RetainAI",
    authorId: "author-013",
    rating: 4.7,
    reviewCount: 143,
    downloadCount: 2100,
    version: "1.5.0",
    publishedAt: "2024-05-22T11:00:00Z",
    updatedAt: "2025-03-25T14:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "ShieldAlert",
  },
  {
    id: "listing-014",
    agentId: "agent-ext-014",
    title: "HR Onboarding Buddy",
    description:
      "Guides new hires through onboarding checklists, answers policy questions, schedules introductory meetings, and collects day-one feedback automatically.",
    category: "productivity",
    authorName: "PeopleFirst AI",
    authorId: "author-014",
    rating: 4.2,
    reviewCount: 88,
    downloadCount: 900,
    version: "1.0.2",
    publishedAt: "2024-08-05T09:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "Users",
  },
  {
    id: "listing-015",
    agentId: "agent-ext-015",
    title: "Legal Document Drafter",
    description:
      "Generates first-draft NDAs, service agreements, and privacy policies based on your inputs. Not a substitute for legal advice, but accelerates your legal team's review cycle significantly.",
    category: "custom",
    authorName: "LexBot Inc",
    authorId: "author-015",
    rating: 4.0,
    reviewCount: 76,
    downloadCount: 700,
    version: "1.1.1",
    publishedAt: "2024-09-01T10:00:00Z",
    updatedAt: "2025-02-05T12:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "FileText",
  },
  {
    id: "listing-016",
    agentId: "agent-ext-016",
    title: "Podcast Show Notes Generator",
    description:
      "Transcribes podcast audio and generates SEO-optimised show notes, timestamps, and key takeaway summaries ready to publish on your website.",
    category: "creative",
    authorName: "AudioMind",
    authorId: "author-016",
    rating: 4.1,
    reviewCount: 59,
    downloadCount: 600,
    version: "1.0.0",
    publishedAt: "2024-09-15T08:00:00Z",
    updatedAt: "2024-12-20T09:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "Mic",
  },
  {
    id: "listing-017",
    agentId: "agent-ext-017",
    title: "Sales Call Coach",
    description:
      "Analyses recorded sales calls for talk ratios, objection handling, and MEDDIC adherence. Provides reps with personalised coaching tips after every call.",
    category: "communication",
    authorName: "CloseMore AI",
    authorId: "author-017",
    rating: 4.5,
    reviewCount: 193,
    downloadCount: 2500,
    version: "2.2.0",
    publishedAt: "2024-04-10T11:00:00Z",
    updatedAt: "2025-04-12T13:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "PhoneCall",
  },
  {
    id: "listing-018",
    agentId: "agent-ext-018",
    title: "Knowledge Base Builder",
    description:
      "Crawls your internal wikis, Confluence spaces, and Notion pages to build a searchable, AI-powered knowledge base. Answers employee questions instantly with cited sources.",
    category: "research",
    authorName: "KnowBot",
    authorId: "author-018",
    rating: 4.3,
    reviewCount: 127,
    downloadCount: 1900,
    version: "1.4.0",
    publishedAt: "2024-06-20T09:00:00Z",
    updatedAt: "2025-03-10T16:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "Database",
  },
  {
    id: "listing-019",
    agentId: "agent-ext-019",
    title: "Invoice Processing Agent",
    description:
      "Extracts line items from PDF invoices, validates against purchase orders, and pushes approved records to QuickBooks or Xero. Reduces accounts payable processing time by 80%.",
    category: "custom",
    authorName: "FinOps Robot",
    authorId: "author-019",
    rating: 4.4,
    reviewCount: 105,
    downloadCount: 1300,
    version: "1.3.2",
    publishedAt: "2024-07-12T10:00:00Z",
    updatedAt: "2025-02-22T11:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "Receipt",
  },
  {
    id: "listing-020",
    agentId: "agent-ext-020",
    title: "Social Listening Agent",
    description:
      "Monitors brand mentions, hashtags, and sentiment across Twitter/X, Reddit, and LinkedIn. Sends real-time alerts for PR crises and surfaces trending topics relevant to your industry.",
    category: "research",
    authorName: "PulseWatch",
    authorId: "author-020",
    rating: 4.2,
    reviewCount: 84,
    downloadCount: 1100,
    version: "1.1.0",
    publishedAt: "2024-08-01T08:00:00Z",
    updatedAt: "2025-01-28T10:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "Radio",
  },
  {
    id: "listing-021",
    agentId: "agent-ext-021",
    title: "Code Review Assistant",
    description:
      "Reviews pull requests for security vulnerabilities, code style violations, and performance bottlenecks. Leaves inline comments and generates a PR summary for reviewers.",
    category: "custom",
    authorName: "DevGuard AI",
    authorId: "author-021",
    rating: 4.6,
    reviewCount: 216,
    downloadCount: 3200,
    version: "2.3.0",
    publishedAt: "2024-03-25T10:00:00Z",
    updatedAt: "2025-04-18T15:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "Code2",
  },
  {
    id: "listing-022",
    agentId: "agent-ext-022",
    title: "Customer Feedback Analyser",
    description:
      "Aggregates reviews from G2, Trustpilot, and app stores. Uses sentiment analysis to identify recurring themes, feature requests, and pain points, then surfaces them in a weekly digest.",
    category: "customer-support",
    authorName: "VoiceOfCustomer",
    authorId: "author-022",
    rating: 3.5,
    reviewCount: 42,
    downloadCount: 200,
    version: "1.0.0",
    publishedAt: "2024-10-01T09:00:00Z",
    updatedAt: "2024-11-05T10:00:00Z",
    isFeatured: false,
    isInstalled: false,
    iconName: "MessageCircle",
  },
]

export const mockMarketplaceKpis: MarketplaceKpis = {
  totalListings: 1248,
  totalDownloads: 45200,
  averageRating: 4.7,
  newThisWeek: 38,
}

export const mockMarketplaceSubscriptions: MarketplaceSubscription[] = [
  {
    id: "sub-001",
    listingId: "listing-001",
    title: "Omnichannel Support Pro",
    category: "customer-support",
    installedVersion: "3.1.0",
    latestVersion: "3.2.1",
    hasUpdate: true,
    installedAt: "2025-02-10T10:00:00Z",
  },
  {
    id: "sub-002",
    listingId: "listing-004",
    title: "TaskFlow Optimizer",
    category: "productivity",
    installedVersion: "2.0.1",
    latestVersion: "2.1.0",
    hasUpdate: true,
    installedAt: "2025-01-20T09:00:00Z",
  },
  {
    id: "sub-003",
    listingId: "listing-010",
    title: "Meeting Summariser",
    category: "productivity",
    installedVersion: "2.0.0",
    latestVersion: "2.0.0",
    hasUpdate: false,
    installedAt: "2025-03-05T14:00:00Z",
  },
  {
    id: "sub-004",
    listingId: "listing-021",
    title: "Code Review Assistant",
    category: "custom",
    installedVersion: "2.1.0",
    latestVersion: "2.3.0",
    hasUpdate: true,
    installedAt: "2025-03-15T11:00:00Z",
  },
  {
    id: "sub-005",
    listingId: "listing-017",
    title: "Sales Call Coach",
    category: "communication",
    installedVersion: "2.2.0",
    latestVersion: "2.2.0",
    hasUpdate: false,
    installedAt: "2025-04-01T08:00:00Z",
  },
]
